dbt_pipeline: # TODO: Change this to your project name
  outputs:
    dev:
      dataset: dbt_pipeline_dev # TODO: Change this to your project name
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../google-service-account-<dbt-pipeline>-runtime.json # TODO: Change this to your project name
      location: EU
      method: service-account
      priority: interactive
      project: alva-analytics
      threads: 1
      type: bigquery
    prod:
      dataset: dbt_pipeline # TODO: Change this to your project name
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../google-service-account-<dbt-pipeline>-runtime.json # TODO: Change this to your project name
      location: EU
      method: service-account
      priority: interactive
      project: alva-analytics
      threads: 1
      type: bigquery
  target: dev
