job_recommendation_interactions:
  outputs:
    dev:
      dataset: job_recommendation_interactions_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../google-service-account-job-rec-interactions-runtime.json
      location: EU
      method: service-account
      priority: interactive
      project: alva-analytics
      threads: 1
      type: bigquery
    prod:
      dataset: job_recommendation_interactions 
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../google-service-account-job-rec-interactions-runtime.json
      location: EU
      method: service-account
      priority: interactive
      project: alva-analytics
      threads: 1
      type: bigquery
  target: dev
