repos:
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 3.2.5
  hooks:
    # - id: sqlfluff-lint
    #   additional_dependencies: ['dbt-bigquery==1.8.3', 'sqlfluff-templater-dbt']
    - id: sqlfluff-fix
      additional_dependencies: ['dbt-bigquery==1.8.3', 'sqlfluff-templater-dbt']