version: 2

sources:

  - name: "contract_batch"
    database: alva-backend
    schema: organization_contract
    freshness:
      warn_after: { count: 2, period: hour }
      error_after: { count: 4, period: hour }
    tables:
      - name: younium_account
      - name: younium_subscription
